import { mutation, internalMutation } from "../_generated/server";
import { v } from "convex/values";
import { getAuthenticatedAppUser } from "../auth";

// Create a new doctor (admin only - for now, anyone can create for development)
export const createDoctor = mutation({
  args: {
    type: v.string(),
    name_en: v.string(),
    name_ar: v.string(),
    name_fr: v.optional(v.string()),
    specialty: v.string(),
    specialty_ar: v.optional(v.string()),
    description_en: v.optional(v.string()),
    description_ar: v.optional(v.string()),
    address: v.string(),
    wilaya: v.string(),
    coordinates: v.object({
      lat: v.number(),
      lng: v.number(),
    }),
    phone: v.optional(v.string()),
    email: v.optional(v.string()),
    workingHours: v.optional(
      v.array(
        v.object({
          day: v.string(),
          open: v.string(),
          close: v.string(),
          isClosed: v.optional(v.boolean()),
        })
      )
    ),
    consultationFee: v.optional(v.number()),
    languages: v.optional(v.array(v.string())),
  },
  handler: async (ctx, args) => {
    const doctorId = await ctx.db.insert("doctors", {
      ...args,
      rating: 0,
      reviewCount: 0,
      isVerified: false,
      isActive: true,
      createdAt: Date.now(),
      updatedAt: Date.now(),
    });

    return doctorId;
  },
});

// Update a doctor
export const updateDoctor = mutation({
  args: {
    doctorId: v.id("doctors"),
    name_en: v.optional(v.string()),
    name_ar: v.optional(v.string()),
    name_fr: v.optional(v.string()),
    specialty: v.optional(v.string()),
    specialty_ar: v.optional(v.string()),
    description_en: v.optional(v.string()),
    description_ar: v.optional(v.string()),
    address: v.optional(v.string()),
    wilaya: v.optional(v.string()),
    coordinates: v.optional(
      v.object({
        lat: v.number(),
        lng: v.number(),
      })
    ),
    phone: v.optional(v.string()),
    email: v.optional(v.string()),
    workingHours: v.optional(
      v.array(
        v.object({
          day: v.string(),
          open: v.string(),
          close: v.string(),
          isClosed: v.optional(v.boolean()),
        })
      )
    ),
    consultationFee: v.optional(v.number()),
    languages: v.optional(v.array(v.string())),
    isActive: v.optional(v.boolean()),
  },
  handler: async (ctx, args) => {
    const { doctorId, ...updates } = args;

    const doctor = await ctx.db.get(doctorId);
    if (!doctor) {
      throw new Error("Doctor not found");
    }

    // Filter out undefined values
    const filteredUpdates: Record<string, unknown> = { updatedAt: Date.now() };
    for (const [key, value] of Object.entries(updates)) {
      if (value !== undefined) {
        filteredUpdates[key] = value;
      }
    }

    await ctx.db.patch(doctorId, filteredUpdates);

    return { success: true };
  },
});

// Add a review for a doctor
export const addReview = mutation({
  args: {
    doctorId: v.id("doctors"),
    appointmentId: v.optional(v.id("appointments")),
    rating: v.number(),
    content: v.optional(v.string()),
    isAnonymous: v.optional(v.boolean()),
  },
  handler: async (ctx, args) => {
    const user = await getAuthenticatedAppUser(ctx);
    if (!user) {
      throw new Error("Not authenticated");
    }

    // Verify doctor exists
    const doctor = await ctx.db.get(args.doctorId);
    if (!doctor) {
      throw new Error("Doctor not found");
    }

    // Validate rating
    if (args.rating < 1 || args.rating > 5) {
      throw new Error("Rating must be between 1 and 5");
    }

    // Check if user has a verified appointment (optional)
    let isVerified = false;
    if (args.appointmentId) {
      const appointment = await ctx.db.get(args.appointmentId);
      if (appointment && appointment.userId === user._id && appointment.status === "completed") {
        isVerified = true;
      }
    }

    // Create the review
    const reviewId = await ctx.db.insert("reviews", {
      userId: user._id,
      doctorId: args.doctorId,
      appointmentId: args.appointmentId,
      rating: args.rating,
      content: args.content,
      isAnonymous: args.isAnonymous || false,
      isVerified,
      createdAt: Date.now(),
      updatedAt: Date.now(),
    });

    // Update doctor's rating
    await updateDoctorRating(ctx, args.doctorId);

    return reviewId;
  },
});

// Internal function to update doctor's average rating
async function updateDoctorRating(ctx: { db: any }, doctorId: string) {
  const reviews = await ctx.db
    .query("reviews")
    .withIndex("by_doctorId", (q: any) => q.eq("doctorId", doctorId))
    .collect();

  if (reviews.length === 0) {
    return;
  }

  const totalRating = reviews.reduce((sum: number, r: { rating: number }) => sum + r.rating, 0);
  const avgRating = totalRating / reviews.length;

  await ctx.db.patch(doctorId, {
    rating: Math.round(avgRating * 10) / 10, // Round to 1 decimal
    reviewCount: reviews.length,
    updatedAt: Date.now(),
  });
}

// Save doctor's working hours schedule
export const saveWorkingHours = mutation({
  args: {
    doctorId: v.id("doctors"),
    workingHours: v.array(
      v.object({
        day: v.string(),
        open: v.string(),
        close: v.string(),
        isClosed: v.optional(v.boolean()),
      })
    ),
    consultationFee: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    const user = await getAuthenticatedAppUser(ctx);
    if (!user || (user.role !== "doctor" && user.role !== "clinic")) {
      throw new Error("Not authorized");
    }

    const doctor = await ctx.db.get(args.doctorId);
    if (!doctor) {
      throw new Error("Doctor not found");
    }

    const updates: Record<string, unknown> = {
      workingHours: args.workingHours,
      updatedAt: Date.now(),
    };

    if (args.consultationFee !== undefined) {
      updates.consultationFee = args.consultationFee;
    }

    await ctx.db.patch(args.doctorId, updates);

    return { success: true };
  },
});

// Block specific dates (create availability schedule entries with all slots unavailable)
export const blockDate = mutation({
  args: {
    doctorId: v.id("doctors"),
    date: v.string(),
  },
  handler: async (ctx, args) => {
    const user = await getAuthenticatedAppUser(ctx);
    if (!user || (user.role !== "doctor" && user.role !== "clinic")) {
      throw new Error("Not authorized");
    }

    // Check if schedule already exists for this date
    const existing = await ctx.db
      .query("availabilitySchedules")
      .withIndex("by_doctorId_and_date", (q) =>
        q.eq("doctorId", args.doctorId).eq("date", args.date)
      )
      .unique();

    if (existing) {
      // Mark all slots as unavailable
      await ctx.db.patch(existing._id, {
        slots: existing.slots.map((s) => ({ ...s, isAvailable: false })),
      });
    } else {
      // Create empty schedule (no slots = day off)
      await ctx.db.insert("availabilitySchedules", {
        doctorId: args.doctorId,
        date: args.date,
        slots: [],
      });
    }

    return { success: true };
  },
});

// Unblock a date
export const unblockDate = mutation({
  args: {
    doctorId: v.id("doctors"),
    date: v.string(),
  },
  handler: async (ctx, args) => {
    const user = await getAuthenticatedAppUser(ctx);
    if (!user || (user.role !== "doctor" && user.role !== "clinic")) {
      throw new Error("Not authorized");
    }

    const existing = await ctx.db
      .query("availabilitySchedules")
      .withIndex("by_doctorId_and_date", (q) =>
        q.eq("doctorId", args.doctorId).eq("date", args.date)
      )
      .unique();

    if (existing) {
      await ctx.db.delete(existing._id);
    }

    return { success: true };
  },
});

// Seed doctors (for development) - Real Algerian doctors from public directories
export const seedDoctors = internalMutation({
  args: {},
  handler: async (ctx) => {
    // Clear existing doctors first to avoid duplicates
    const existing = await ctx.db.query("doctors").collect();
    for (const doc of existing) {
      await ctx.db.delete(doc._id);
    }

    const sampleDoctors = [
      // === CARDIOLOGISTS ===
      {
        type: "doctor",
        name_en: "Dr. Brahim Kandi",
        name_ar: "د. إبراهيم كاندي",
        name_fr: "Dr Brahim KANDI",
        specialty: "cardiology",
        specialty_ar: "أمراض القلب",
        address: "Cours AISSAT IDIR HLM Bt 9, El Harrach 16200, Alger",
        wilaya: "Alger",
        coordinates: { lat: 36.7166, lng: 3.1340 },
        phone: "+213 021521104",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Souad Zebentout",
        name_ar: "د. سعاد زبنطوط",
        name_fr: "Dr Souad ZEBENTOUT",
        specialty: "cardiology",
        specialty_ar: "أمراض القلب",
        address: "30 Rue Didouche Mourad, Alger Centre 16008, Alger",
        wilaya: "Alger",
        coordinates: { lat: 36.7700, lng: 3.0588 },
        phone: "+213 021968263",
        consultationFee: 3500,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Belhadj Mostefa Zoubir",
        name_ar: "د. بلحاج مصطفى زوبير",
        name_fr: "Dr Belhadj Mostefa Zoubir",
        specialty: "cardiology",
        specialty_ar: "أمراض القلب",
        address: "6 Rue des Frères Boutamine Bellevue, Constantine 25000",
        wilaya: "Constantine",
        coordinates: { lat: 36.3650, lng: 6.6147 },
        phone: "+213 559666300",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      // === DERMATOLOGISTS ===
      {
        type: "doctor",
        name_en: "Dr. Naima Amrouche-Maouche",
        name_ar: "د. نعيمة عمروش ماوش",
        name_fr: "Dr Naïma AMROUCHE-MAOUCHE",
        specialty: "dermatology",
        specialty_ar: "الأمراض الجلدية",
        address: "08, Rue Omar Benkhettab B.E.O, Alger 16008",
        wilaya: "Alger",
        coordinates: { lat: 36.7631, lng: 3.0506 },
        phone: "+213 021962398",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Fatiha Cheikh",
        name_ar: "د. فتيحة شيخ",
        name_fr: "Dr Fatiha CHEIKH",
        specialty: "dermatology",
        specialty_ar: "الأمراض الجلدية",
        address: "2 Rue Moulay Med, Oran 31000",
        wilaya: "Oran",
        coordinates: { lat: 35.6969, lng: -0.6331 },
        phone: "+213 041395957",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Latifa Lessel",
        name_ar: "د. لطيفة لصل",
        name_fr: "Dr Latifa LESSEL",
        specialty: "dermatology",
        specialty_ar: "الأمراض الجلدية",
        address: "Résidence des Marguerites, Bloc A 1er étage, Hai El Yasmine, Bir el Djir 31130, Oran",
        wilaya: "Oran",
        coordinates: { lat: 35.7200, lng: -0.5900 },
        phone: "+213 041661923",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      // === OPHTHALMOLOGISTS ===
      {
        type: "doctor",
        name_en: "Dr. Djelloul Damerdji",
        name_ar: "د. جلول دمرجي",
        name_fr: "Dr Djelloul DAMERDJI",
        specialty: "ophthalmology",
        specialty_ar: "طب العيون",
        address: "30 Rue Balzac (ex Carteaux), Oran 31000",
        wilaya: "Oran",
        coordinates: { lat: 35.6975, lng: -0.6350 },
        phone: "+213 041823485",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Mustapha Meziane",
        name_ar: "د. مصطفى مزيان",
        name_fr: "Dr Mustapha MEZIANE",
        specialty: "ophthalmology",
        specialty_ar: "طب العيون",
        address: "Oran Centre, Oran 31000",
        wilaya: "Oran",
        coordinates: { lat: 35.6950, lng: -0.6400 },
        phone: "+213 041322366",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      // === GYNECOLOGISTS ===
      {
        type: "doctor",
        name_en: "Dr. Abdelouahab Nabti",
        name_ar: "د. عبد الوهاب نابتي",
        name_fr: "Dr Abdelouahab NABTI",
        specialty: "gynecology",
        specialty_ar: "أمراض النساء والتوليد",
        address: "Cité 20 Août Bt D7 N° 382, Sétif 19000",
        wilaya: "Sétif",
        coordinates: { lat: 36.1905, lng: 5.4080 },
        phone: "+213 036849192",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Boukhezza Amina",
        name_ar: "د. بوخزة أمينة",
        name_fr: "Dr Boukhezza Amina",
        specialty: "gynecology",
        specialty_ar: "أمراض النساء والتوليد",
        address: "Cité El Rym Plaine West 02, Bat N° K03, 1er étage N°29, Annaba 23000",
        wilaya: "Annaba",
        coordinates: { lat: 36.9000, lng: 7.7667 },
        phone: "+213 038832524",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      // === ORTHOPEDIC SURGEONS ===
      {
        type: "doctor",
        name_en: "Dr. Djillali Aouak",
        name_ar: "د. جيلالي عواك",
        name_fr: "Dr Djillali AOUAK",
        specialty: "orthopedics",
        specialty_ar: "جراحة العظام",
        address: "Place de la Liberté N°1, Boufarik 9400, Blida",
        wilaya: "Blida",
        coordinates: { lat: 36.3725, lng: 2.9130 },
        phone: "+213 025474129",
        consultationFee: 3500,
        languages: ["ar", "fr"],
      },
      // === NEUROLOGISTS ===
      {
        type: "doctor",
        name_en: "Dr. Djamila Mahmoudi",
        name_ar: "د. جميلة محمودي",
        name_fr: "Dr Djamila MAHMOUDI",
        specialty: "neurology",
        specialty_ar: "أمراض الأعصاب",
        address: "4, Rue Patrice Lumumba, Alger Centre 16000, Alger",
        wilaya: "Alger",
        coordinates: { lat: 36.7753, lng: 3.0588 },
        phone: "+213 021715650",
        consultationFee: 3500,
        languages: ["ar", "fr"],
      },
      // === ENT SPECIALISTS ===
      {
        type: "doctor",
        name_en: "Dr. Benabed S.",
        name_ar: "د. بن عابد",
        name_fr: "Dr BENABED S.",
        specialty: "ent",
        specialty_ar: "أنف أذن حنجرة",
        address: "Cité 633 Logts Bloc B, 1er étage, Bel Horizon, Bir el Djir 31130, Oran",
        wilaya: "Oran",
        coordinates: { lat: 35.7175, lng: -0.5850 },
        phone: "+213 797515857",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Abdelhamid Nourredine",
        name_ar: "د. عبد الحميد نور الدين",
        name_fr: "Dr Abdelhamid NOURREDINE",
        specialty: "ent",
        specialty_ar: "أنف أذن حنجرة",
        address: "2, Rue Lachheb Rabah Cne, Constantine 25000",
        wilaya: "Constantine",
        coordinates: { lat: 36.3600, lng: 6.6100 },
        phone: "+213 031949689",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Mohamed Ghimouz",
        name_ar: "د. محمد غيموز",
        name_fr: "Dr Mohamed GHIMOUZ",
        specialty: "ent",
        specialty_ar: "أنف أذن حنجرة",
        address: "4, Rue des Volontaires, Cours de la Révolution, Annaba 23000",
        wilaya: "Annaba",
        coordinates: { lat: 36.9044, lng: 7.7524 },
        phone: "+213 038459059",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      // === GASTROENTEROLOGISTS ===
      {
        type: "doctor",
        name_en: "Dr. Mourad Djeha",
        name_ar: "د. مراد جحا",
        name_fr: "Dr Mourad DJEHA",
        specialty: "gastroenterology",
        specialty_ar: "أمراض الجهاز الهضمي",
        address: "2ème étage, 05 Rue Abane Ramdane, Alger Centre 16000, Alger",
        wilaya: "Alger",
        coordinates: { lat: 36.7700, lng: 3.0600 },
        phone: "+213 044171579",
        consultationFee: 3500,
        languages: ["ar", "fr"],
      },
      // === UROLOGISTS ===
      {
        type: "doctor",
        name_en: "Dr. Abdelkader Karkouri",
        name_ar: "د. عبد القادر كركوري",
        name_fr: "Dr Abdelkader KARKOURI",
        specialty: "urology",
        specialty_ar: "أمراض المسالك البولية",
        address: "Pharmacie Bensahli Bab Dzair, Blida 9000",
        wilaya: "Blida",
        coordinates: { lat: 36.4700, lng: 2.8283 },
        phone: "+213 025418302",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Amar Challab",
        name_ar: "د. عمار شلاب",
        name_fr: "Dr Amar CHALLAB",
        specialty: "urology",
        specialty_ar: "أمراض المسالك البولية",
        address: "Lotissement Alioua Fodil, Cheraga 16002, Alger",
        wilaya: "Alger",
        coordinates: { lat: 36.7610, lng: 2.9500 },
        phone: "+213 774971652",
        consultationFee: 3500,
        languages: ["ar", "fr"],
      },
      // === PULMONOLOGISTS ===
      {
        type: "doctor",
        name_en: "Dr. Mustapha Ouslim",
        name_ar: "د. مصطفى وسليم",
        name_fr: "Dr Mustapha OUSLIM",
        specialty: "pulmonology",
        specialty_ar: "أمراض الرئة",
        address: "40, Bd Benzerdjeb, Oran 31000",
        wilaya: "Oran",
        coordinates: { lat: 35.6930, lng: -0.6350 },
        phone: "+213 041404221",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Abdelkader Dahou",
        name_ar: "د. عبد القادر داحو",
        name_fr: "Dr Abdelkader DAHOU",
        specialty: "pulmonology",
        specialty_ar: "أمراض الرئة",
        address: "23 Rue de Lourcq Bt.B Delmonte, Oran 31000",
        wilaya: "Oran",
        coordinates: { lat: 35.6985, lng: -0.6310 },
        phone: "+213 041455055",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      // === PSYCHIATRISTS ===
      {
        type: "doctor",
        name_en: "Dr. Abdennebi Ahmed",
        name_ar: "د. عبد النبي أحمد",
        name_fr: "Dr ABDENNEBI Ahmed",
        specialty: "psychiatry",
        specialty_ar: "الطب النفسي",
        address: "2 Rue Benkhedda, Place du 1er Novembre, Blida 9000",
        wilaya: "Blida",
        coordinates: { lat: 36.4700, lng: 2.8280 },
        phone: "+213 025401513",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Said Daara",
        name_ar: "د. سعيد دعارة",
        name_fr: "Dr Said DAARA",
        specialty: "psychiatry",
        specialty_ar: "الطب النفسي",
        address: "Centre-ville, Annaba 23000",
        wilaya: "Annaba",
        coordinates: { lat: 36.9000, lng: 7.7530 },
        phone: "+213 038455946",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      // === DENTISTS ===
      {
        type: "doctor",
        name_en: "Dr. Ali Siad",
        name_ar: "د. علي صياد",
        name_fr: "Dr Ali SIAD",
        specialty: "dentist",
        specialty_ar: "طب الأسنان",
        address: "9, Rue du 20 Août 1956, Azazga 15300, Tizi Ouzou",
        wilaya: "Tizi Ouzou",
        coordinates: { lat: 36.7450, lng: 4.3710 },
        phone: "+213 026141346",
        consultationFee: 1500,
        languages: ["ar", "fr", "kab"],
      },
      {
        type: "doctor",
        name_en: "Dr. Tahar Gazou",
        name_ar: "د. طاهر قازو",
        name_fr: "Dr Tahar GAZOU",
        specialty: "dentist",
        specialty_ar: "طب الأسنان",
        address: "Immeuble Abdelli, Place du Stade 1er Novembre, Tizi Ouzou 15000",
        wilaya: "Tizi Ouzou",
        coordinates: { lat: 36.7117, lng: 4.0457 },
        phone: "+213 026219622",
        consultationFee: 1500,
        languages: ["ar", "fr", "kab"],
      },
      {
        type: "doctor",
        name_en: "Dr. Abdelouahab Tfyeche",
        name_ar: "د. عبد الوهاب تفياش",
        name_fr: "Dr Abdelouahab TFYECHE",
        specialty: "dentist",
        specialty_ar: "طب الأسنان",
        address: "08 Rue Koura Bacha, Blida 9000",
        wilaya: "Blida",
        coordinates: { lat: 36.4690, lng: 2.8280 },
        phone: "+213 558253914",
        consultationFee: 1500,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Mohcene Boudjellal",
        name_ar: "د. محسن بوجلال",
        name_fr: "Dr Mohcene BOUDJELLAL",
        specialty: "dentist",
        specialty_ar: "طب الأسنان",
        address: "101 Rue Maatar Lakhdar, Annaba 23000",
        wilaya: "Annaba",
        coordinates: { lat: 36.9020, lng: 7.7560 },
        phone: "+213 038834500",
        consultationFee: 1500,
        languages: ["ar", "fr"],
      },
      // === PEDIATRICIANS ===
      {
        type: "doctor",
        name_en: "Dr. Redouane Bekhtari",
        name_ar: "د. رضوان بختاري",
        name_fr: "Dr Redouane BEKHTARI",
        specialty: "pediatrics",
        specialty_ar: "طب الأطفال",
        address: "Cité Soumam, Bâtiment D1 N° 04, Boufarik 9400, Blida",
        wilaya: "Blida",
        coordinates: { lat: 36.3730, lng: 2.9140 },
        phone: "+213 025482417",
        consultationFee: 2000,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Lilia Bensalah",
        name_ar: "د. ليليا بن صالح",
        name_fr: "Dr Lilia BENSALAH",
        specialty: "pediatrics",
        specialty_ar: "طب الأطفال",
        address: "2 Boulevard Bouzared Hocine, Annaba 23000",
        wilaya: "Annaba",
        coordinates: { lat: 36.9035, lng: 7.7590 },
        phone: "+213 038405617",
        consultationFee: 2000,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Bensaid D.",
        name_ar: "د. بن سعيد",
        name_fr: "Dr BENSAID D.",
        specialty: "pediatrics",
        specialty_ar: "طب الأطفال",
        address: "Cité 600 Logts BT 23 N° 01/361, Zouaghi Slimane, Constantine 25000",
        wilaya: "Constantine",
        coordinates: { lat: 36.3400, lng: 6.6300 },
        phone: "+213 031703210",
        consultationFee: 2000,
        languages: ["ar", "fr"],
      },
      // === GENERAL PRACTITIONERS ===
      {
        type: "doctor",
        name_en: "Dr. Said Assal",
        name_ar: "د. سعيد عسال",
        name_fr: "Dr Said ASSAL",
        specialty: "general",
        specialty_ar: "طب عام",
        address: "Lot Est N° 34, Zeralda 16063, Alger",
        wilaya: "Alger",
        coordinates: { lat: 36.7116, lng: 2.8389 },
        phone: "+213 021320709",
        consultationFee: 1500,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Abdelatif Benabdallah",
        name_ar: "د. عبد اللطيف بن عبد الله",
        name_fr: "Dr Abdelatif BENABDALLAH",
        specialty: "general",
        specialty_ar: "طب عام",
        address: "62, Bd Benzerdjeb, Oran 31000",
        wilaya: "Oran",
        coordinates: { lat: 35.6940, lng: -0.6340 },
        phone: "+213 041415010",
        consultationFee: 1500,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Fatiha Benzadi",
        name_ar: "د. فتيحة بن زادي",
        name_fr: "Dr Fatiha BENZADI",
        specialty: "general",
        specialty_ar: "طب عام",
        address: "Cité Daski, Bâtiment 2, N° 878, Constantine 25000",
        wilaya: "Constantine",
        coordinates: { lat: 36.3550, lng: 6.6200 },
        phone: "+213 031739700",
        consultationFee: 1500,
        languages: ["ar", "fr"],
      },
      // === CLINICS & HOSPITALS — ALGER (10) ===
      {
        type: "clinic",
        name_en: "Clinique Al Azhar",
        name_ar: "عيادة الأزهر",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "4, Djenane Achabou, Dely Brahim, 16000, Alger",
        wilaya: "Alger",
        coordinates: { lat: 36.7585, lng: 2.9833 },
        phone: "+213 23 18 80 80",
        consultationFee: 4000,
        languages: ["ar", "fr"],
      },
      {
        type: "clinic",
        name_en: "Clinique Reefak El Feth",
        name_ar: "عيادة رفاق الفتح",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "Ouled Fayet, Alger",
        wilaya: "Alger",
        coordinates: { lat: 36.7260, lng: 2.8920 },
        phone: "+213 555 08 07 49",
        consultationFee: 3500,
        languages: ["ar", "fr"],
      },
      {
        type: "clinic",
        name_en: "Clinique Aya",
        name_ar: "عيادة آية",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "Cite Sorecal, Birkhadem, Alger",
        wilaya: "Alger",
        coordinates: { lat: 36.7144, lng: 3.0500 },
        phone: "+213 21 54 00 00",
        consultationFee: 4000,
        languages: ["ar", "fr"],
      },
      {
        type: "clinic",
        name_en: "Clinique Diar Saada",
        name_ar: "عيادة ديار السعادة",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "100, Chemin Abdelkader, El Mouradia, 16000, Alger",
        wilaya: "Alger",
        coordinates: { lat: 36.7475, lng: 3.0475 },
        phone: "+213 21 69 13 13",
        consultationFee: 4500,
        languages: ["ar", "fr"],
      },
      {
        type: "clinic",
        name_en: "Clinique Ennour",
        name_ar: "عيادة النور",
        specialty: "gastroenterology",
        specialty_ar: "أمراض الجهاز الهضمي",
        address: "El Madania, Alger",
        wilaya: "Alger",
        coordinates: { lat: 36.7420, lng: 3.0600 },
        phone: "+213 21 68 50 50",
        consultationFee: 3500,
        languages: ["ar", "fr"],
      },
      {
        type: "clinic",
        name_en: "Clinique Chifa",
        name_ar: "عيادة الشفاء",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "Hydra, Alger",
        wilaya: "Alger",
        coordinates: { lat: 36.7430, lng: 3.0270 },
        phone: "+213 21 69 27 27",
        consultationFee: 5000,
        languages: ["ar", "fr", "en"],
      },
      {
        type: "clinic",
        name_en: "Clinique du Val",
        name_ar: "عيادة الوادي",
        specialty: "general",
        specialty_ar: "طب عام",
        address: "Hydra, Alger",
        wilaya: "Alger",
        coordinates: { lat: 36.7440, lng: 3.0250 },
        phone: "+213 21 48 13 13",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "clinic",
        name_en: "Clinique Les Vergers",
        name_ar: "عيادة البساتين",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "Birkhadem, Alger",
        wilaya: "Alger",
        coordinates: { lat: 36.7170, lng: 3.0480 },
        phone: "+213 21 55 30 30",
        consultationFee: 3500,
        languages: ["ar", "fr"],
      },
      {
        type: "clinic",
        name_en: "Clinique Bir Mourad Rais",
        name_ar: "عيادة بئر مراد رايس",
        specialty: "ophthalmology",
        specialty_ar: "طب العيون",
        address: "Said Hamdine, Bir Mourad Rais, Alger",
        wilaya: "Alger",
        coordinates: { lat: 36.7280, lng: 3.0400 },
        phone: "+213 21 54 77 77",
        consultationFee: 4000,
        languages: ["ar", "fr"],
      },
      {
        type: "clinic",
        name_en: "Clinique Jihan Hana",
        name_ar: "عيادة جيهان هنا",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "Reghaia, Alger",
        wilaya: "Alger",
        coordinates: { lat: 36.7340, lng: 3.3400 },
        phone: "+213 21 84 50 50",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      // === CLINICS — ORAN (8) ===
      {
        type: "clinic",
        name_en: "Clinique de la Vision - Chiali Lasik",
        name_ar: "مركز شيالي لتصحيح البصر",
        specialty: "ophthalmology",
        specialty_ar: "طب العيون",
        address: "63, Boulevard les Castors, Oran",
        wilaya: "Oran",
        coordinates: { lat: 35.6950, lng: -0.6430 },
        phone: "+213 777 87 49 91",
        consultationFee: 4000,
        languages: ["ar", "fr"],
      },
      {
        type: "clinic",
        name_en: "Clinique Echiffa",
        name_ar: "عيادة الشفاء",
        specialty: "nephrology",
        specialty_ar: "أمراض الكلى",
        address: "5 Rue Hadj Frih Daifallah, Sidi Senouci, Oran",
        wilaya: "Oran",
        coordinates: { lat: 35.6980, lng: -0.6290 },
        phone: "+213 41 25 17 20",
        consultationFee: 3500,
        languages: ["ar", "fr"],
      },
      {
        type: "hospital",
        name_en: "Etablissement Hospitalier Privé Kara",
        name_ar: "المؤسسة الاستشفائية الخاصة قارة",
        specialty: "cardiology",
        specialty_ar: "أمراض القلب",
        address: "Route Nationale 2A, Es-Senia, Oran",
        wilaya: "Oran",
        coordinates: { lat: 35.6520, lng: -0.6530 },
        phone: "+213 41 61 44 67",
        consultationFee: 5000,
        languages: ["ar", "fr"],
      },
      {
        type: "clinic",
        name_en: "Clinique Bensarai",
        name_ar: "عيادة بن سراي",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "55, Avenue Grine Belkacem, Sananes, Oran",
        wilaya: "Oran",
        coordinates: { lat: 35.7000, lng: -0.6260 },
        phone: "+213 41 21 86 86",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "clinic",
        name_en: "Clinique Ennedjah",
        name_ar: "عيادة النجاح",
        specialty: "gynecology",
        specialty_ar: "أمراض النساء والتوليد",
        address: "Rond des Trois Cliniques, USTO, Oran",
        wilaya: "Oran",
        coordinates: { lat: 35.7060, lng: -0.6170 },
        phone: "+213 41 53 09 07",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "clinic",
        name_en: "Clinique Ilies",
        name_ar: "عيادة إلياس",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "50, Boulevard Abbou Dahran, Rond-Point des Castors, Oran",
        wilaya: "Oran",
        coordinates: { lat: 35.6955, lng: -0.6440 },
        phone: "+213 41 46 39 56",
        consultationFee: 3500,
        languages: ["ar", "fr"],
      },
      {
        type: "clinic",
        name_en: "Clinique Deddouche",
        name_ar: "عيادة دادوش",
        specialty: "gynecology",
        specialty_ar: "أمراض النساء والتوليد",
        address: "10 Avenue Bessaoud Abdellah, Gambetta, Oran",
        wilaya: "Oran",
        coordinates: { lat: 35.6975, lng: -0.6370 },
        phone: "+213 41 53 32 17",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "clinic",
        name_en: "Clinique El Anis",
        name_ar: "عيادة الأنيس",
        specialty: "gynecology",
        specialty_ar: "أمراض النساء والتوليد",
        address: "24, Rue Alexandre Lunoi, Gambetta, Oran",
        wilaya: "Oran",
        coordinates: { lat: 35.6970, lng: -0.6380 },
        phone: "+213 41 53 12 70",
        consultationFee: 4500,
        languages: ["ar", "fr"],
      },
      // === CLINICS — CONSTANTINE (6) ===
      {
        type: "clinic",
        name_en: "Clinique El Anouar",
        name_ar: "عيادة الأنوار",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "17 Cite Achouri Mohamed, Plateau Mansourah, Constantine",
        wilaya: "Constantine",
        coordinates: { lat: 36.3400, lng: 6.6070 },
        phone: "+213 31 91 00 00",
        consultationFee: 3500,
        languages: ["ar", "fr"],
      },
      {
        type: "clinic",
        name_en: "Clinique Ezzahra",
        name_ar: "عيادة الزهراء",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "15, Boulevard des Cliniques, Zouaghi Slimane, Constantine",
        wilaya: "Constantine",
        coordinates: { lat: 36.3280, lng: 6.6350 },
        phone: "+213 560 94 60 84",
        consultationFee: 3500,
        languages: ["ar", "fr"],
      },
      {
        type: "clinic",
        name_en: "Athena Medical Center",
        name_ar: "مركز أثينا الطبي",
        specialty: "oncology",
        specialty_ar: "علم الأورام",
        address: "6 Boulevard des Cliniques, Cite 1100 Logement Zouaghi, Constantine",
        wilaya: "Constantine",
        coordinates: { lat: 36.3290, lng: 6.6340 },
        phone: "+213 31 69 25 88",
        consultationFee: 5000,
        languages: ["ar", "fr"],
      },
      {
        type: "clinic",
        name_en: "Clinique Daghbouche",
        name_ar: "عيادة دغبوش",
        specialty: "ophthalmology",
        specialty_ar: "طب العيون",
        address: "28 S, Cite Eucalyptus, Ain El Bey, Constantine",
        wilaya: "Constantine",
        coordinates: { lat: 36.3120, lng: 6.6250 },
        phone: "+213 31 90 99 99",
        consultationFee: 3500,
        languages: ["ar", "fr"],
      },
      {
        type: "clinic",
        name_en: "Clinique Naoufel",
        name_ar: "عيادة نوفل",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "Cite Belhadj, Ain El Bey, Constantine",
        wilaya: "Constantine",
        coordinates: { lat: 36.3100, lng: 6.6230 },
        phone: "+213 31 90 09 44",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "clinic",
        name_en: "Clinique Boukerrou",
        name_ar: "عيادة بوكروا",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "Lotissement Bab El Djedid 26/28, Ain El Bey, Constantine",
        wilaya: "Constantine",
        coordinates: { lat: 36.3080, lng: 6.6200 },
        phone: "+213 31 89 50 92",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      // === CLINICS — ANNABA (3) ===
      {
        type: "clinic",
        name_en: "Clinique El Djazair",
        name_ar: "عيادة الجزائر",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "Rue Amar Bouzid, Cite des Peupliers, Plaine Ouest II, 23000, Annaba",
        wilaya: "Annaba",
        coordinates: { lat: 36.9000, lng: 7.7667 },
        phone: "+213 38 41 49 39",
        consultationFee: 3500,
        languages: ["ar", "fr"],
      },
      {
        type: "clinic",
        name_en: "Clinique Al Farabi",
        name_ar: "عيادة الفارابي",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "21-23 Rue Ahcene Chaouch Mohamed Kamel, L'Orangerie, Annaba",
        wilaya: "Annaba",
        coordinates: { lat: 36.8980, lng: 7.7580 },
        phone: "+213 38 43 43 00",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "clinic",
        name_en: "Clinique Bellevue Elysa",
        name_ar: "عيادة بلفو إليزا",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "Route de Seraidi, Annaba",
        wilaya: "Annaba",
        coordinates: { lat: 36.9120, lng: 7.7550 },
        phone: "+213 38 42 74 38",
        consultationFee: 3500,
        languages: ["ar", "fr"],
      },
      // === CLINICS — SÉTIF (2) ===
      {
        type: "clinic",
        name_en: "Clinique Radjah",
        name_ar: "عيادة رجاح",
        specialty: "cardiology",
        specialty_ar: "أمراض القلب",
        address: "Cite Tlidjene Local 406, Sétif",
        wilaya: "Sétif",
        coordinates: { lat: 36.1910, lng: 5.4140 },
        phone: "+213 36 93 90 90",
        consultationFee: 3500,
        languages: ["ar", "fr"],
      },
      {
        type: "clinic",
        name_en: "Clinique Renaissance",
        name_ar: "عيادة النهضة",
        specialty: "general",
        specialty_ar: "طب عام",
        address: "Cite 220 Lots N49, El Hidhab, Sétif",
        wilaya: "Sétif",
        coordinates: { lat: 36.1850, lng: 5.4080 },
        phone: "+213 36 63 91 34",
        consultationFee: 2000,
        languages: ["ar", "fr"],
      },
      // === CLINICS — BLIDA (2) ===
      {
        type: "clinic",
        name_en: "Clinique Atlas",
        name_ar: "عيادة الأطلس",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "Rue Cherif Chalabi, Blida",
        wilaya: "Blida",
        coordinates: { lat: 36.4700, lng: 2.8300 },
        phone: "+213 25 41 27 25",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "clinic",
        name_en: "Clinique Zoulikha",
        name_ar: "عيادة زوليخة",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "02 Rue El Bey Khaled, Blida",
        wilaya: "Blida",
        coordinates: { lat: 36.4720, lng: 2.8270 },
        phone: "+213 25 41 07 13",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      // === CLINICS — TLEMCEN (2) ===
      {
        type: "clinic",
        name_en: "Clinique Benhabib",
        name_ar: "عيادة بن حبيب",
        specialty: "pediatrics",
        specialty_ar: "طب الأطفال",
        address: "Lot 752, Les Amandiers, Kiffane, Tlemcen",
        wilaya: "Tlemcen",
        coordinates: { lat: 34.8828, lng: -1.3150 },
        phone: "+213 43 20 68 10",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      {
        type: "clinic",
        name_en: "Clinique Les Dahlias",
        name_ar: "عيادة الداليا",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "Mansourah, Tlemcen",
        wilaya: "Tlemcen",
        coordinates: { lat: 34.8600, lng: -1.3350 },
        phone: "+213 43 27 50 50",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      // === CLINICS — BATNA (2) ===
      {
        type: "clinic",
        name_en: "Clinique Les Cèdres",
        name_ar: "عيادة الأرز",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "Lot Zenati Zmala, Batna",
        wilaya: "Batna",
        coordinates: { lat: 35.5559, lng: 6.1743 },
        phone: "+213 33 86 50 50",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      {
        type: "clinic",
        name_en: "Clinique Ibn Sina",
        name_ar: "عيادة ابن سينا",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "Route de Tazoult, Batna",
        wilaya: "Batna",
        coordinates: { lat: 35.5570, lng: 6.1750 },
        phone: "+213 33 80 20 20",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      // === CLINICS — DJELFA (2) ===
      {
        type: "hospital",
        name_en: "Etablissement Hospitalier Privé Naila",
        name_ar: "المؤسسة الاستشفائية الخاصة نائلة",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "Cité Berbih Bd N°06 Lots 164, Propriété 99, Djelfa 17000",
        wilaya: "Djelfa",
        coordinates: { lat: 34.6725, lng: 3.2500 },
        phone: "+213 27 93 93 46",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      {
        type: "hospital",
        name_en: "Hôpital d'Ophtalmologie Algérie-Cuba",
        name_ar: "مستشفى طب العيون الجزائر-كوبا",
        specialty: "ophthalmology",
        specialty_ar: "طب العيون",
        address: "Rue Administrative, Djelfa 17000",
        wilaya: "Djelfa",
        coordinates: { lat: 34.6740, lng: 3.2560 },
        phone: "+213 27 93 66 74",
        consultationFee: 2000,
        languages: ["ar", "fr"],
      },
      // === CLINICS — BISKRA (2) ===
      {
        type: "clinic",
        name_en: "Clinique Okba Ibn Nafaa",
        name_ar: "عيادة عقبة بن نافع",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "Cite El Alia El Chamalia, 07000, Biskra",
        wilaya: "Biskra",
        coordinates: { lat: 34.8449, lng: 5.7281 },
        phone: "+213 33 74 50 50",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      {
        type: "clinic",
        name_en: "Clinique Er-Razi",
        name_ar: "عيادة الرازي",
        specialty: "general",
        specialty_ar: "طب عام",
        address: "Rue Amri A, Hai El Moudjahidine, Biskra",
        wilaya: "Biskra",
        coordinates: { lat: 34.8420, lng: 5.7300 },
        phone: "+213 33 73 20 20",
        consultationFee: 2000,
        languages: ["ar", "fr"],
      },
      // === CLINICS — BÉJAÏA (2) ===
      {
        type: "clinic",
        name_en: "Clinique Dr Belaid",
        name_ar: "عيادة الدكتور بلعيد",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "Boulevard de la Liberté, Béjaïa",
        wilaya: "Béjaïa",
        coordinates: { lat: 36.7509, lng: 5.0567 },
        phone: "+213 34 21 50 50",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "clinic",
        name_en: "Clinique Oualid d'Ophtalmologie",
        name_ar: "عيادة وليد لطب العيون",
        specialty: "ophthalmology",
        specialty_ar: "طب العيون",
        address: "Tazmalt, Béjaïa",
        wilaya: "Béjaïa",
        coordinates: { lat: 36.3920, lng: 4.4020 },
        phone: "+213 34 35 20 20",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      // === CLINICS — TIZI OUZOU (2) ===
      {
        type: "clinic",
        name_en: "Clinique Centrale",
        name_ar: "العيادة المركزية",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "54 Avenue Abane Ramdane, Tizi Ouzou",
        wilaya: "Tizi Ouzou",
        coordinates: { lat: 36.7117, lng: 4.0453 },
        phone: "+213 26 12 22 60",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "clinic",
        name_en: "Clinique Slimana",
        name_ar: "عيادة سليمانة",
        specialty: "neurology",
        specialty_ar: "طب الأعصاب",
        address: "Zhun Sud Quartier A, Tizi Ouzou",
        wilaya: "Tizi Ouzou",
        coordinates: { lat: 36.7050, lng: 4.0500 },
        phone: "+213 26 21 68 68",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      // === CLINICS — MOSTAGANEM (2) ===
      {
        type: "clinic",
        name_en: "Clinique El Habib",
        name_ar: "عيادة الحبيب",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "Place 1 Novembre 54, Centre Ville, Mostaganem",
        wilaya: "Mostaganem",
        coordinates: { lat: 35.9311, lng: 0.0882 },
        phone: "+213 45 21 45 74",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      {
        type: "clinic",
        name_en: "Clinique Kharoubi",
        name_ar: "عيادة خروبي",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "Cite Chemouma, Mostaganem",
        wilaya: "Mostaganem",
        coordinates: { lat: 35.9350, lng: 0.0850 },
        phone: "+213 45 21 26 26",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      // === CLINICS — CHLEF (1) ===
      {
        type: "clinic",
        name_en: "Clinique Les Orangers",
        name_ar: "عيادة البرتقال",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "Boulevard Colonel Lotfi, Chlef",
        wilaya: "Chlef",
        coordinates: { lat: 36.1654, lng: 1.3339 },
        phone: "+213 27 77 50 50",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      // === CLINICS — M'SILA (1) ===
      {
        type: "clinic",
        name_en: "Clinique El Hayat",
        name_ar: "عيادة الحياة",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "Cite 1000 Logements, M'sila",
        wilaya: "M'sila",
        coordinates: { lat: 35.7056, lng: 4.5425 },
        phone: "+213 35 55 30 30",
        consultationFee: 2000,
        languages: ["ar", "fr"],
      },
      // === CLINICS — TIARET (1) ===
      {
        type: "clinic",
        name_en: "Clinique El Amel",
        name_ar: "عيادة الأمل",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "Boulevard Emir Abdelkader, Tiaret",
        wilaya: "Tiaret",
        coordinates: { lat: 35.3711, lng: 1.3171 },
        phone: "+213 46 42 30 30",
        consultationFee: 2000,
        languages: ["ar", "fr"],
      },
      // === CLINICS — MÉDÉA (1) ===
      {
        type: "clinic",
        name_en: "Clinique Bendifallah",
        name_ar: "عيادة بن ضيف الله",
        specialty: "gynecology",
        specialty_ar: "أمراض النساء والتوليد",
        address: "Rue Ben Boulaid, Médéa",
        wilaya: "Médéa",
        coordinates: { lat: 36.2675, lng: 2.7500 },
        phone: "+213 25 58 30 30",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      // === CLINICS — SKIKDA (1) ===
      {
        type: "clinic",
        name_en: "Clinique Abou Al Qassim",
        name_ar: "عيادة أبو القاسم",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "Les Allées du 20 Août 55, Skikda",
        wilaya: "Skikda",
        coordinates: { lat: 36.8764, lng: 6.9061 },
        phone: "+213 38 72 25 25",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      // === CLINICS — JIJEL (1) ===
      {
        type: "clinic",
        name_en: "Clinique El Wouroud",
        name_ar: "عيادة الورود",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "Boulevard Bouali, Jijel",
        wilaya: "Jijel",
        coordinates: { lat: 36.8210, lng: 5.7663 },
        phone: "+213 34 47 30 30",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      // === CLINICS — BORDJ BOU ARRÉRIDJ (1) ===
      {
        type: "clinic",
        name_en: "Clinique Boutahar Errahmane",
        name_ar: "عيادة بوطاهر الرحمان",
        specialty: "multi-specialty",
        specialty_ar: "متعددة التخصصات",
        address: "N95, Cite des 90 Logements, El-Djebbes, Bordj Bou Arréridj",
        wilaya: "Bordj Bou Arréridj",
        coordinates: { lat: 36.0667, lng: 4.7500 },
        phone: "+213 35 69 12 12",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      // === CLINICS — NAOUFEL DENTAL CENTER, CONSTANTINE ===
      {
        type: "clinic",
        name_en: "Naoufel Dental Center",
        name_ar: "مركز نوفل لطب الأسنان",
        specialty: "dentist",
        specialty_ar: "طب الأسنان",
        address: "Rue des Frères Lezzar, Constantine 25000",
        wilaya: "Constantine",
        coordinates: { lat: 36.3650, lng: 6.6150 },
        phone: "+213 559 20 07 28",
        consultationFee: 2000,
        languages: ["ar", "fr"],
      },
      // =============================================
      // === NEW DOCTORS — BATCH 2 (35 doctors) ===
      // =============================================
      // === CARDIOLOGISTS (3) ===
      {
        type: "doctor",
        name_en: "Dr. Karima Settouti Habour",
        name_ar: "د. كريمة ستوتي حبور",
        name_fr: "Dr Karima SETTOUTI HABOUR",
        specialty: "cardiology",
        specialty_ar: "أمراض القلب",
        address: "9, Avenue Larbi Tebessi, Oran 31000",
        wilaya: "Oran",
        coordinates: { lat: 35.6971, lng: -0.6331 },
        phone: "+213 041335734",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Mohamed Sofiane Amara",
        name_ar: "د. محمد سفيان عمارة",
        name_fr: "Dr Mohamed Sofiane AMARA",
        specialty: "cardiology",
        specialty_ar: "أمراض القلب",
        address: "Cité Daksi Bt 07 bis N° 3, Constantine 25001",
        wilaya: "Constantine",
        coordinates: { lat: 36.3555, lng: 6.6210 },
        phone: "+213 031637827",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Bibak Farida",
        name_ar: "د. بيبك فريدة",
        name_fr: "Dr Bibak Farida",
        specialty: "cardiology",
        specialty_ar: "أمراض القلب",
        address: "419 Ali Mendjli Nouvelle Ville, Constantine 25000",
        wilaya: "Constantine",
        coordinates: { lat: 36.2600, lng: 6.5900 },
        phone: "+213 031748484",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      // === DENTISTS (3) ===
      {
        type: "doctor",
        name_en: "Dr. Touaa Youcef Ryad",
        name_ar: "د. طوعا يوسف رياض",
        name_fr: "Dr TOUAA Youcef Ryad",
        specialty: "dentist",
        specialty_ar: "طب الأسنان",
        address: "72 Rue Didouche Mourad, Alger Centre 16000, Alger",
        wilaya: "Alger",
        coordinates: { lat: 36.7700, lng: 3.0580 },
        phone: "+213 555595587",
        consultationFee: 2000,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Hocine Kaouther",
        name_ar: "د. حسين كوثر",
        name_fr: "Dr Hocine Kaouther",
        specialty: "dentist",
        specialty_ar: "طب الأسنان",
        address: "09 Rue Reda Houhou, Alger 16000",
        wilaya: "Alger",
        coordinates: { lat: 36.7680, lng: 3.0560 },
        phone: "+213 555296210",
        consultationFee: 1500,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. S. Ladjabi",
        name_ar: "د. لجابي",
        name_fr: "Dr S. LADJABI",
        specialty: "dentist",
        specialty_ar: "طب الأسنان",
        address: "Ali Mendjeli Nouvelle Ville, Constantine 25016",
        wilaya: "Constantine",
        coordinates: { lat: 36.2580, lng: 6.5850 },
        phone: "+213 540040070",
        consultationFee: 1500,
        languages: ["ar", "fr"],
      },
      // === DERMATOLOGISTS (3) ===
      {
        type: "doctor",
        name_en: "Dr. Kadi Faiza",
        name_ar: "د. قادي فايزة",
        name_fr: "Dr KADI Faiza",
        specialty: "dermatology",
        specialty_ar: "الأمراض الجلدية",
        address: "Bir Mourad Rais, Alger 16200",
        wilaya: "Alger",
        coordinates: { lat: 36.7280, lng: 3.0410 },
        phone: "+213 561894299",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Azeddine Cherrad",
        name_ar: "د. عز الدين شراد",
        name_fr: "Dr Azeddine CHERRAD",
        specialty: "dermatology",
        specialty_ar: "الأمراض الجلدية",
        address: "4, Rue Merimeche Cne, Constantine 25000",
        wilaya: "Constantine",
        coordinates: { lat: 36.3650, lng: 6.6130 },
        phone: "+213 031920345",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. T. Lefkir",
        name_ar: "د. لفقير",
        name_fr: "Dr T. LEFKIR",
        specialty: "dermatology",
        specialty_ar: "الأمراض الجلدية",
        address: "790 Logt, Bt 609/E3, RDC, USTO face à la SEOR, Oran 31000",
        wilaya: "Oran",
        coordinates: { lat: 35.7100, lng: -0.6200 },
        phone: "+213 773999887",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      // === PEDIATRICIANS (3) ===
      {
        type: "doctor",
        name_en: "Dr. Fortas Cherifa",
        name_ar: "د. فرطاس شريفة",
        name_fr: "Dr FORTAS Cherifa",
        specialty: "pediatrics",
        specialty_ar: "طب الأطفال",
        address: "11 Rue Abderrahmane Hami, Bab El Oued, Alger 16008",
        wilaya: "Alger",
        coordinates: { lat: 36.7900, lng: 3.0480 },
        phone: "+213 021969107",
        consultationFee: 2000,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Rachid Taleb Bendiab",
        name_ar: "د. رشيد طالب بن دياب",
        name_fr: "Dr Rachid TALEB BENDIAB",
        specialty: "pediatrics",
        specialty_ar: "طب الأطفال",
        address: "Groupe de Lattre de Tassigny, Oran 31000",
        wilaya: "Oran",
        coordinates: { lat: 35.6950, lng: -0.6370 },
        phone: "+213 041406767",
        consultationFee: 2000,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Mohamed Moulay Omar",
        name_ar: "د. محمد مولاي عمر",
        name_fr: "Dr Mohamed MOULAY OMAR",
        specialty: "pediatrics",
        specialty_ar: "طب الأطفال",
        address: "Centre-ville, Blida 9000",
        wilaya: "Blida",
        coordinates: { lat: 36.4700, lng: 2.8290 },
        phone: "+213 025460321",
        consultationFee: 2000,
        languages: ["ar", "fr"],
      },
      // === GENERAL PRACTITIONERS (3) ===
      {
        type: "doctor",
        name_en: "Dr. Ali Saib",
        name_ar: "د. علي صايب",
        name_fr: "Dr Ali SAIB",
        specialty: "general",
        specialty_ar: "طب عام",
        address: "Cité des 48 Logts Ben Boulaid, Blida 9000",
        wilaya: "Blida",
        coordinates: { lat: 36.4690, lng: 2.8310 },
        phone: "+213 025414500",
        consultationFee: 1500,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Amina Benaissa",
        name_ar: "د. أمينة بن عيسى",
        name_fr: "Dr Amina BENAISSA",
        specialty: "general",
        specialty_ar: "طب عام",
        address: "29 Bd Principal Hai Bouamama, Oran 31000",
        wilaya: "Oran",
        coordinates: { lat: 35.6960, lng: -0.6350 },
        phone: "+213 041395000",
        consultationFee: 1500,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Noureddine Bencheikh",
        name_ar: "د. نور الدين بن شيخ",
        name_fr: "Dr Noureddine BENCHEIKH",
        specialty: "general",
        specialty_ar: "طب عام",
        address: "Cité Rivet, Blida 9000",
        wilaya: "Blida",
        coordinates: { lat: 36.4710, lng: 2.8260 },
        phone: "+213 025410500",
        consultationFee: 1500,
        languages: ["ar", "fr"],
      },
      // === OPHTHALMOLOGISTS (3) ===
      {
        type: "doctor",
        name_en: "Dr. Rezki Ihaddadene",
        name_ar: "د. رزقي إحدادن",
        name_fr: "Dr Rezki IHADDADENE",
        specialty: "ophthalmology",
        specialty_ar: "طب العيون",
        address: "Centre Oculus, Blida 9000",
        wilaya: "Blida",
        coordinates: { lat: 36.4710, lng: 2.8280 },
        phone: "+213 025323269",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Karim Benahmed",
        name_ar: "د. كريم بن أحمد",
        name_fr: "Dr Karim BENAHMED",
        specialty: "ophthalmology",
        specialty_ar: "طب العيون",
        address: "02 Bd Che Guevara, Annaba 23000",
        wilaya: "Annaba",
        coordinates: { lat: 36.9030, lng: 7.7540 },
        phone: "+213 038458800",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Kameche Ibrahim El Khalil",
        name_ar: "د. كامش إبراهيم الخليل",
        name_fr: "Dr Kameche Ibrahim El Khalil",
        specialty: "ophthalmology",
        specialty_ar: "طب العيون",
        address: "Place de la Liberté, Bab Essebt, Blida 9000",
        wilaya: "Blida",
        coordinates: { lat: 36.4695, lng: 2.8275 },
        phone: "+213 799380260",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      // === GYNECOLOGISTS (3) ===
      {
        type: "doctor",
        name_en: "Dr. Lilia Benghida Amari",
        name_ar: "د. ليليا بن غيدة عماري",
        name_fr: "Dr Lilia BENGHIDA AMARI",
        specialty: "gynecology",
        specialty_ar: "أمراض النساء والتوليد",
        address: "6, Rue des Volontaires, Annaba 23000",
        wilaya: "Annaba",
        coordinates: { lat: 36.9040, lng: 7.7530 },
        phone: "+213 038459089",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Latifa Bouchene",
        name_ar: "د. لطيفة بوشان",
        name_fr: "Dr Latifa BOUCHENE",
        specialty: "gynecology",
        specialty_ar: "أمراض النساء والتوليد",
        address: "26 Rue Didouche Mourad, Alger Centre, Alger 16000",
        wilaya: "Alger",
        coordinates: { lat: 36.7700, lng: 3.0585 },
        phone: "+213 021635221",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Naima Karabernou",
        name_ar: "د. نعيمة قرابرنو",
        name_fr: "Dr Naima KARABERNOU",
        specialty: "gynecology",
        specialty_ar: "أمراض النساء والتوليد",
        address: "117bis Rue Ramli, Bouzareah 16340, Alger",
        wilaya: "Alger",
        coordinates: { lat: 36.7830, lng: 3.0120 },
        phone: "+213 021903256",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      // === ORTHOPEDIC SURGEONS (2) ===
      {
        type: "doctor",
        name_en: "Dr. Rachid Benselama",
        name_ar: "د. رشيد بن سلامة",
        name_fr: "Dr Rachid BENSELAMA",
        specialty: "orthopedics",
        specialty_ar: "جراحة العظام",
        address: "Cité des Anassers 2, Bt 4 E3, Kouba 16050, Alger",
        wilaya: "Alger",
        coordinates: { lat: 36.7230, lng: 3.0810 },
        phone: "+213 021293016",
        consultationFee: 3500,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Abdelhakim Mokrane",
        name_ar: "د. عبد الحكيم مقران",
        name_fr: "Dr MOKRANE Abdelhakim",
        specialty: "orthopedics",
        specialty_ar: "جراحة العظام",
        address: "22 Rue Med Belouizdad 1er Mai, Sidi M'Hamed, Alger 16000",
        wilaya: "Alger",
        coordinates: { lat: 36.7530, lng: 3.0620 },
        phone: "+213 021652787",
        consultationFee: 3500,
        languages: ["ar", "fr"],
      },
      // === NEUROLOGISTS (2) ===
      {
        type: "doctor",
        name_en: "Dr. Mokhtar Sbia",
        name_ar: "د. مختار صبيعة",
        name_fr: "Dr Mokhtar SBIA",
        specialty: "neurology",
        specialty_ar: "أمراض الأعصاب",
        address: "Passage face 39 Rue Boudiaf, au dos du Marché Plateaux, Oran 31000",
        wilaya: "Oran",
        coordinates: { lat: 35.6980, lng: -0.6340 },
        phone: "+213 041360179",
        consultationFee: 3500,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Seloua Zahdour",
        name_ar: "د. سلوى زهدور",
        name_fr: "Dr Seloua ZAHDOUR",
        specialty: "neurology",
        specialty_ar: "أمراض الأعصاب",
        address: "30 Bd Hamou Boutlelis, Oran 31000",
        wilaya: "Oran",
        coordinates: { lat: 35.6965, lng: -0.6380 },
        phone: "+213 041391964",
        consultationFee: 3500,
        languages: ["ar", "fr"],
      },
      // === INTERNAL MEDICINE (2) ===
      {
        type: "doctor",
        name_en: "Dr. Djamel Yacini",
        name_ar: "د. جمال ياسيني",
        name_fr: "Dr YACINI Djamel",
        specialty: "internal_medicine",
        specialty_ar: "الطب الداخلي",
        address: "03, Rue Ahmed Touzen B.E.O, Bab El Oued, Alger 16000",
        wilaya: "Alger",
        coordinates: { lat: 36.7890, lng: 3.0490 },
        phone: "+213 021960500",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Sidali Benkanoun",
        name_ar: "د. سيد علي بن كانون",
        name_fr: "Dr BENKANOUN Sidali",
        specialty: "internal_medicine",
        specialty_ar: "الطب الداخلي",
        address: "286, Boulevard Colonel Bougara, Bâtiment E, Cité Africana, El Biar, Alger 16000",
        wilaya: "Alger",
        coordinates: { lat: 36.7620, lng: 3.0300 },
        phone: "+213 021925500",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      // === ENDOCRINOLOGISTS (2) ===
      {
        type: "doctor",
        name_en: "Dr. Chakib Khalloua Ali",
        name_ar: "د. شكيب خلوة علي",
        name_fr: "Dr Chakib KHALLOUA ALI",
        specialty: "endocrinology",
        specialty_ar: "أمراض الغدد الصماء",
        address: "Cité 160 Logements (Pyramides) Bloc 01, en face de l'EHU, USTO, Bir el Djir 31130, Oran",
        wilaya: "Oran",
        coordinates: { lat: 35.7150, lng: -0.6080 },
        phone: "+213 041705975",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Djaoued Fasla",
        name_ar: "د. جاود فصلة",
        name_fr: "Dr Djaoued FASLA",
        specialty: "endocrinology",
        specialty_ar: "أمراض الغدد الصماء",
        address: "5, Rue Murochaux, Oran 31000",
        wilaya: "Oran",
        coordinates: { lat: 35.6970, lng: -0.6360 },
        phone: "+213 041402894",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      // === RHEUMATOLOGISTS (2) ===
      {
        type: "doctor",
        name_en: "Dr. Riad Chiheub",
        name_ar: "د. رياض شيهوب",
        name_fr: "Dr Riad CHIHEUB",
        specialty: "rheumatology",
        specialty_ar: "أمراض الروماتيزم",
        address: "Cité Nouvelle N° 44, Didouche Mourad 25210, Constantine",
        wilaya: "Constantine",
        coordinates: { lat: 36.3580, lng: 6.6280 },
        phone: "+213 031905473",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Mohamed Boukredera",
        name_ar: "د. محمد بوكريدرة",
        name_fr: "Dr Mohamed BOUKREDERA",
        specialty: "rheumatology",
        specialty_ar: "أمراض الروماتيزم",
        address: "Cité Boudjenana Bt D1 N° 482, Constantine 25000",
        wilaya: "Constantine",
        coordinates: { lat: 36.3600, lng: 6.6180 },
        phone: "+213 031640500",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      // === DENTIST — ANNABA (1 more) ===
      {
        type: "doctor",
        name_en: "Dr. Oudjani Noureddine",
        name_ar: "د. وجاني نور الدين",
        name_fr: "Dr OUDJANI Noureddine",
        specialty: "dentist",
        specialty_ar: "طب الأسنان",
        address: "Centre-ville, Annaba 23000",
        wilaya: "Annaba",
        coordinates: { lat: 36.9010, lng: 7.7550 },
        phone: "+213 699889884",
        consultationFee: 1500,
        languages: ["ar", "fr"],
      },
      // === PEDIATRICIAN — ANNABA (1 more) ===
      {
        type: "doctor",
        name_en: "Dr. Riad Nacer",
        name_ar: "د. رياض ناصر",
        name_fr: "Dr Riad NACER",
        specialty: "pediatrics",
        specialty_ar: "طب الأطفال",
        address: "Centre-ville, Annaba 23000",
        wilaya: "Annaba",
        coordinates: { lat: 36.9015, lng: 7.7535 },
        phone: "+213 030820253",
        consultationFee: 2000,
        languages: ["ar", "fr"],
      },
      // === NEPHROLOGISTS (2) ===
      {
        type: "doctor",
        name_en: "Dr. Oualid Atamnia",
        name_ar: "د. وليد عطمنية",
        name_fr: "Dr Oualid ATAMNIA",
        specialty: "nephrology",
        specialty_ar: "أمراض الكلى",
        address: "Clinique El Djazair, Plaine Ouest 2, Annaba 23000",
        wilaya: "Annaba",
        coordinates: { lat: 36.8990, lng: 7.7650 },
        phone: "+213 775673353",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Nour Eddine Manseur",
        name_ar: "د. نور الدين منصور",
        name_fr: "Dr Nour Eddine MANSEUR",
        specialty: "nephrology",
        specialty_ar: "أمراض الكلى",
        address: "9 Rue Khemisti, Annaba 23000",
        wilaya: "Annaba",
        coordinates: { lat: 36.9025, lng: 7.7520 },
        phone: "+213 038866444",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      // =============================================
      // === NEW DOCTORS — BATCH 3 (35 doctors) ===
      // === Smaller & Medium Cities of Algeria ===
      // =============================================
      // === SÉTIF (3) ===
      {
        type: "doctor",
        name_en: "Dr. Mustafa Saidi",
        name_ar: "د. مصطفى سعيدي",
        name_fr: "Dr Mustafa SAIDI",
        specialty: "cardiology",
        specialty_ar: "أمراض القلب",
        address: "Cité Le Caire, Sétif 19000",
        wilaya: "Sétif",
        coordinates: { lat: 36.1905, lng: 5.4120 },
        phone: "+213 036939927",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Salim Guessoum",
        name_ar: "د. سليم قسوم",
        name_fr: "Dr Salim GUESSOUM",
        specialty: "ophthalmology",
        specialty_ar: "طب العيون",
        address: "Cité des 1000 Logts BTC8 N103, Sétif 19000",
        wilaya: "Sétif",
        coordinates: { lat: 36.1870, lng: 5.4050 },
        phone: "+213 036847818",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Alaa Chafai",
        name_ar: "د. آلاء شفاعي",
        name_fr: "Dr Alaa CHAFAI",
        specialty: "dentist",
        specialty_ar: "طب الأسنان",
        address: "Cité Bouaroua 5lot N°235 Centre Commercial Bouaroua, Sétif 19000",
        wilaya: "Sétif",
        coordinates: { lat: 36.1930, lng: 5.4100 },
        phone: "+213 662623401",
        consultationFee: 1500,
        languages: ["ar", "fr"],
      },
      // === TLEMCEN (2) ===
      {
        type: "doctor",
        name_en: "Dr. M. Habchi",
        name_ar: "د. م. حبشي",
        name_fr: "Dr M. HABCHI",
        specialty: "dentist",
        specialty_ar: "طب الأسنان",
        address: "Boulevard Imame Ali, Résidence Yasmine, Mansourah, Tlemcen 13000",
        wilaya: "Tlemcen",
        coordinates: { lat: 34.8600, lng: -1.3300 },
        phone: "+213 043218888",
        consultationFee: 2000,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Nasreddine El Oued",
        name_ar: "د. نصر الدين الوعد",
        name_fr: "Dr Nasreddine EL OUED",
        specialty: "psychiatry",
        specialty_ar: "الطب النفسي",
        address: "03 Place Cheikh Ibrahim, Tlemcen 13000",
        wilaya: "Tlemcen",
        coordinates: { lat: 34.8828, lng: -1.3170 },
        phone: "+213 043271968",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      // === BATNA (4) ===
      {
        type: "doctor",
        name_en: "Dr. Brahim Merad",
        name_ar: "د. إبراهيم مراد",
        name_fr: "Dr Brahim MERAD",
        specialty: "cardiology",
        specialty_ar: "أمراض القلب",
        address: "Centre-ville, Batna 05000",
        wilaya: "Batna",
        coordinates: { lat: 35.5559, lng: 6.1740 },
        phone: "+213 033804800",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Cherif Belhiouani",
        name_ar: "د. شريف بلحيواني",
        name_fr: "Dr Cherif BELHIOUANI",
        specialty: "ent",
        specialty_ar: "أنف أذن حنجرة",
        address: "Cité Ecotec 410 Logts, Batna 05000",
        wilaya: "Batna",
        coordinates: { lat: 35.5580, lng: 6.1780 },
        phone: "+213 033813535",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Noureddine Chikhi",
        name_ar: "د. نور الدين شيخي",
        name_fr: "Dr Noureddine CHIKHI",
        specialty: "gynecology",
        specialty_ar: "أمراض النساء والتوليد",
        address: "5 Rue Abdesmad Abdelmajid, Batna 05000",
        wilaya: "Batna",
        coordinates: { lat: 35.5555, lng: 6.1730 },
        phone: "+213 033804821",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Faiza Meziani",
        name_ar: "د. فايزة مزياني",
        name_fr: "Dr Faiza MEZIANI",
        specialty: "general",
        specialty_ar: "طب عام",
        address: "U S Said Sahraoui, Batna 05000",
        wilaya: "Batna",
        coordinates: { lat: 35.5565, lng: 6.1750 },
        phone: "+213 033803939",
        consultationFee: 1500,
        languages: ["ar", "fr"],
      },
      // === BISKRA (1) ===
      {
        type: "doctor",
        name_en: "Dr. Fayçal Miloudi",
        name_ar: "د. فيصل ميلودي",
        name_fr: "Dr Fayçal MILOUDI",
        specialty: "pediatrics",
        specialty_ar: "طب الأطفال",
        address: "26 Rue Hakim Saadene, Biskra 07000",
        wilaya: "Biskra",
        coordinates: { lat: 34.8449, lng: 5.7281 },
        phone: "+213 033745731",
        consultationFee: 2000,
        languages: ["ar", "fr"],
      },
      // === BÉJAÏA (2) ===
      {
        type: "doctor",
        name_en: "Dr. Farida Moussaoui Ep. Dahmani",
        name_ar: "د. فريدة موساوي دحماني",
        name_fr: "Dr Farida MOUSSAOUI EP. DAHMANI",
        specialty: "gynecology",
        specialty_ar: "أمراض النساء والتوليد",
        address: "21 Cité Nouvelle Zerara, Béjaïa 06000",
        wilaya: "Béjaïa",
        coordinates: { lat: 36.7509, lng: 5.0567 },
        phone: "+213 034214492",
        consultationFee: 3000,
        languages: ["ar", "fr", "kab"],
      },
      {
        type: "doctor",
        name_en: "Dr. Abdelaziz Zaidi",
        name_ar: "د. عبد العزيز زايدي",
        name_fr: "Dr Abdelaziz ZAIDI",
        specialty: "general",
        specialty_ar: "طب عام",
        address: "09 Rue Ouabdelkader Cité Tobal, Béjaïa 06000",
        wilaya: "Béjaïa",
        coordinates: { lat: 36.7520, lng: 5.0580 },
        phone: "+213 034229782",
        consultationFee: 1500,
        languages: ["ar", "fr", "kab"],
      },
      // === TIZI OUZOU (2) ===
      {
        type: "doctor",
        name_en: "Dr. Hocine Timsi",
        name_ar: "د. حسين تيمسي",
        name_fr: "Dr Hocine TIMSI",
        specialty: "ent",
        specialty_ar: "أنف أذن حنجرة",
        address: "Rue des Frères Begaz, Tizi Ouzou 15000",
        wilaya: "Tizi Ouzou",
        coordinates: { lat: 36.7117, lng: 4.0457 },
        phone: "+213 026216827",
        consultationFee: 2500,
        languages: ["ar", "fr", "kab"],
      },
      {
        type: "doctor",
        name_en: "Dr. Hocine Saheb",
        name_ar: "د. حسين ساحب",
        name_fr: "Dr Hocine SAHEB",
        specialty: "dermatology",
        specialty_ar: "الأمراض الجلدية",
        address: "1 Rue des Frères Beggaz Bloc C N°02, La Nouvelle Ville, Tizi Ouzou 15000",
        wilaya: "Tizi Ouzou",
        coordinates: { lat: 36.7130, lng: 4.0470 },
        phone: "+213 026115970",
        consultationFee: 2500,
        languages: ["ar", "fr", "kab"],
      },
      // === MOSTAGANEM (2) ===
      {
        type: "doctor",
        name_en: "Dr. Nacera Amamra",
        name_ar: "د. نصيرة عمامرة",
        name_fr: "Dr Nacera AMAMRA",
        specialty: "cardiology",
        specialty_ar: "أمراض القلب",
        address: "Cité des 320 Lgts Bt 24, Mostaganem 27000",
        wilaya: "Mostaganem",
        coordinates: { lat: 35.9311, lng: 0.0882 },
        phone: "+213 045213015",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Madani Kara Mostefa",
        name_ar: "د. مدني قارة مصطفى",
        name_fr: "Dr Madani KARA MOSTEFA",
        specialty: "dermatology",
        specialty_ar: "الأمراض الجلدية",
        address: "8 Rue Khelifa Mohamed, Mostaganem 27000",
        wilaya: "Mostaganem",
        coordinates: { lat: 35.9330, lng: 0.0900 },
        phone: "+213 045210500",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      // === CHLEF (2) ===
      {
        type: "doctor",
        name_en: "Dr. Benyoucef Boughari",
        name_ar: "د. بن يوسف بوغاري",
        name_fr: "Dr Benyoucef BOUGHARI",
        specialty: "general",
        specialty_ar: "طب عام",
        address: "Zone 5, Chettia 02170, Chlef",
        wilaya: "Chlef",
        coordinates: { lat: 36.1900, lng: 1.2600 },
        phone: "+213 027733427",
        consultationFee: 1500,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Abdelkader Bouazdia",
        name_ar: "د. عبد القادر بوعزدية",
        name_fr: "Dr Abdelkader BOUAZDIA",
        specialty: "dentist",
        specialty_ar: "طب الأسنان",
        address: "04 Rue Ghoulami Mohamed, Boukadir 02300, Chlef",
        wilaya: "Chlef",
        coordinates: { lat: 36.0650, lng: 1.1250 },
        phone: "+213 027740976",
        consultationFee: 1500,
        languages: ["ar", "fr"],
      },
      // === M'SILA (1) ===
      {
        type: "doctor",
        name_en: "Dr. Ali Boudia Hadj",
        name_ar: "د. علي بودية حاج",
        name_fr: "Dr Ali BOUDIA HADJ",
        specialty: "general",
        specialty_ar: "طب عام",
        address: "Cité 20 Août, M'Sila 28000",
        wilaya: "M'sila",
        coordinates: { lat: 35.7056, lng: 4.5425 },
        phone: "+213 035555777",
        consultationFee: 1500,
        languages: ["ar", "fr"],
      },
      // === TIARET (2) ===
      {
        type: "doctor",
        name_en: "Dr. Lakhdar Senisna",
        name_ar: "د. لخضر سنيسنة",
        name_fr: "Dr Lakhdar SENISNA",
        specialty: "cardiology",
        specialty_ar: "أمراض القلب",
        address: "Cité Med Djahlene Bâtiment 52 A2, Tiaret Ouest 14000",
        wilaya: "Tiaret",
        coordinates: { lat: 35.3711, lng: 1.3171 },
        phone: "+213 046211349",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Amar Saadi",
        name_ar: "د. عمار سعدي",
        name_fr: "Dr Amar SAADI",
        specialty: "ophthalmology",
        specialty_ar: "طب العيون",
        address: "Rue Maghraoui Touhami, Tiaret 14000",
        wilaya: "Tiaret",
        coordinates: { lat: 35.3720, lng: 1.3180 },
        phone: "+213 046413056",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      // === MÉDÉA (1) ===
      {
        type: "doctor",
        name_en: "Dr. Abdenour Benameur",
        name_ar: "د. عبد النور بن عامر",
        name_fr: "Dr Abdenour BENAMEUR",
        specialty: "cardiology",
        specialty_ar: "أمراض القلب",
        address: "Cité M'Sallah Bt 8, Médéa 26000",
        wilaya: "Médéa",
        coordinates: { lat: 36.2675, lng: 2.7500 },
        phone: "+213 025783080",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      // === SKIKDA (2) ===
      {
        type: "doctor",
        name_en: "Dr. Abdelhamid Messaoudi",
        name_ar: "د. عبد الحميد مسعودي",
        name_fr: "Dr Abdelhamid MESSAOUDI",
        specialty: "general",
        specialty_ar: "طب عام",
        address: "2 R. Kaddid N°18, Skikda 21000",
        wilaya: "Skikda",
        coordinates: { lat: 36.8764, lng: 6.9061 },
        phone: "+213 038761721",
        consultationFee: 1500,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Laidi Mosbah",
        name_ar: "د. العيدي مصباح",
        name_fr: "Dr Laidi MOSBAH",
        specialty: "pulmonology",
        specialty_ar: "أمراض الرئة",
        address: "1 C 700 Logt Bt 03, Skikda 21000",
        wilaya: "Skikda",
        coordinates: { lat: 36.8770, lng: 6.9070 },
        phone: "+213 038704173",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      // === JIJEL (2) ===
      {
        type: "doctor",
        name_en: "Dr. Samia Nasri Ounes",
        name_ar: "د. سامية نصري عونس",
        name_fr: "Dr Samia NASRI OUNES",
        specialty: "cardiology",
        specialty_ar: "أمراض القلب",
        address: "Cité 200 Logts Bt A3, Jijel 18000",
        wilaya: "Jijel",
        coordinates: { lat: 36.8210, lng: 5.7663 },
        phone: "+213 034496955",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Abdenaceur Kihal",
        name_ar: "د. عبد الناصر كحال",
        name_fr: "Dr Abdenaceur KIHAL",
        specialty: "psychiatry",
        specialty_ar: "الطب النفسي",
        address: "Cité 200 Logts, Bt 6 A3, Jijel 18000",
        wilaya: "Jijel",
        coordinates: { lat: 36.8215, lng: 5.7670 },
        phone: "+213 034490500",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      // === BORDJ BOU ARRÉRIDJ (1) ===
      {
        type: "doctor",
        name_en: "Dr. Azedinne Chenouf",
        name_ar: "د. عز الدين شنوف",
        name_fr: "Dr Azedinne CHENOUF",
        specialty: "ophthalmology",
        specialty_ar: "طب العيون",
        address: "Centre-ville, Bordj Bou Arréridj 34000",
        wilaya: "Bordj Bou Arréridj",
        coordinates: { lat: 36.0667, lng: 4.7500 },
        phone: "+213 035680500",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      // === DJELFA (1) ===
      {
        type: "doctor",
        name_en: "Dr. Hassiba Lahreche",
        name_ar: "د. حسيبة لحرش",
        name_fr: "Dr Hassiba LAHRECHE",
        specialty: "general",
        specialty_ar: "طب عام",
        address: "Centre-ville, Djelfa 17000",
        wilaya: "Djelfa",
        coordinates: { lat: 34.6725, lng: 3.2500 },
        phone: "+213 027873119",
        consultationFee: 1500,
        languages: ["ar", "fr"],
      },
      // === GHARDAÏA (2) ===
      {
        type: "doctor",
        name_en: "Dr. Mohamed Bouchaib Bahaz",
        name_ar: "د. محمد بوشعيب باحاز",
        name_fr: "Dr Mohamed BOUCHAIB BAHAZ",
        specialty: "gastroenterology",
        specialty_ar: "أمراض الجهاز الهضمي",
        address: "Avenue du 1er Novembre, Ghardaïa 47000",
        wilaya: "Ghardaïa",
        coordinates: { lat: 32.4910, lng: 3.6740 },
        phone: "+213 029886060",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Rachid Menana",
        name_ar: "د. رشيد منانة",
        name_fr: "Dr Rachid MENANA",
        specialty: "gynecology",
        specialty_ar: "أمراض النساء والتوليد",
        address: "1 Rue d'Alger, Ghardaïa 47000",
        wilaya: "Ghardaïa",
        coordinates: { lat: 32.4920, lng: 3.6730 },
        phone: "+213 029883701",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      // === OUARGLA (1) ===
      {
        type: "doctor",
        name_en: "Dr. Belkhir Abess",
        name_ar: "د. بلخير عباس",
        name_fr: "Dr Belkhir ABESS",
        specialty: "radiology",
        specialty_ar: "الأشعة",
        address: "Cité Si El Haouas 1850 Logt N°27, Hassi Messaoud 30500, Ouargla",
        wilaya: "Ouargla",
        coordinates: { lat: 31.6800, lng: 6.0644 },
        phone: "+213 029737500",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      // === EL OUED (1) ===
      {
        type: "doctor",
        name_en: "Dr. Abdallah Laadjal",
        name_ar: "د. عبد الله لعجال",
        name_fr: "Dr Abdallah LAADJAL",
        specialty: "general",
        specialty_ar: "طب عام",
        address: "Djamaa, El Oued 39240",
        wilaya: "El Oued",
        coordinates: { lat: 33.5311, lng: 5.9803 },
        phone: "+213 032257358",
        consultationFee: 1500,
        languages: ["ar", "fr"],
      },
      // === SAÏDA (2) ===
      {
        type: "doctor",
        name_en: "Dr. Khedidja Mokhtari",
        name_ar: "د. خديجة مختاري",
        name_fr: "Dr Khedidja MOKHTARI",
        specialty: "pediatrics",
        specialty_ar: "طب الأطفال",
        address: "Lot 32 N°27 Boukada Elgaz, Saïda 20000",
        wilaya: "Saïda",
        coordinates: { lat: 34.8303, lng: 0.1530 },
        phone: "+213 771451795",
        consultationFee: 2000,
        languages: ["ar", "fr"],
      },
      {
        type: "doctor",
        name_en: "Dr. Driss Cheikh",
        name_ar: "د. إدريس شيخ",
        name_fr: "Dr Driss CHEIKH",
        specialty: "dermatology",
        specialty_ar: "الأمراض الجلدية",
        address: "Cité Boudia Bloc 01 N°24, Saïda 20000",
        wilaya: "Saïda",
        coordinates: { lat: 34.8310, lng: 0.1520 },
        phone: "+213 048524327",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      // === SIDI BEL ABBÈS (1) ===
      {
        type: "doctor",
        name_en: "Dr. Hakim Baoune",
        name_ar: "د. حكيم باعون",
        name_fr: "Dr Hakim BAOUNE",
        specialty: "urology",
        specialty_ar: "أمراض المسالك البولية",
        address: "32 Avenue de la Gare, Sidi Bel Abbès 22000",
        wilaya: "Sidi Bel Abbès",
        coordinates: { lat: 35.1897, lng: -0.6308 },
        phone: "+213 048540500",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      // === MASCARA (1) ===
      {
        type: "doctor",
        name_en: "Dr. Abdelkader Belbachir",
        name_ar: "د. عبد القادر بلبشير",
        name_fr: "Dr Abdelkader BELBACHIR",
        specialty: "dermatology",
        specialty_ar: "الأمراض الجلدية",
        address: "1 Rue Benzohra Abdelkader, Mohammédia 29400, Mascara",
        wilaya: "Mascara",
        coordinates: { lat: 35.5630, lng: 0.0820 },
        phone: "+213 045878317",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      // === RELIZANE (1) ===
      {
        type: "doctor",
        name_en: "Dr. Fatima Fortas Omrani",
        name_ar: "د. فاطمة فرطاس عمراني",
        name_fr: "Dr Fatima FORTAS OMRANI",
        specialty: "dermatology",
        specialty_ar: "الأمراض الجلدية",
        address: "Cité des 88 Logts Bt B1 N°4, Relizane 48000",
        wilaya: "Relizane",
        coordinates: { lat: 35.7372, lng: 0.5567 },
        phone: "+213 046926993",
        consultationFee: 2500,
        languages: ["ar", "fr"],
      },
      // === AÏN TÉMOUCHENT (1) ===
      {
        type: "doctor",
        name_en: "Dr. Abderrahim Sellah",
        name_ar: "د. عبد الرحيم صلاح",
        name_fr: "Dr Abderrahim SELLAH",
        specialty: "cardiology",
        specialty_ar: "أمراض القلب",
        address: "11 Rue Abid Djelloul, Aïn Témouchent 46000",
        wilaya: "Aïn Témouchent",
        coordinates: { lat: 35.2977, lng: -1.1403 },
        phone: "+213 043785714",
        consultationFee: 3000,
        languages: ["ar", "fr"],
      },
      // === BOUIRA (2) ===
      {
        type: "doctor",
        name_en: "Dr. Sadia Ait El Hocine",
        name_ar: "د. سعدية آيت الحسين",
        name_fr: "Dr Sadia AIT EL HOCINE EP. AIT BENAMAR",
        specialty: "internal_medicine",
        specialty_ar: "الطب الداخلي",
        address: "Lot 166 Villa 114, Bouira 10000",
        wilaya: "Bouira",
        coordinates: { lat: 36.3800, lng: 3.9000 },
        phone: "+213 026939531",
        consultationFee: 3000,
        languages: ["ar", "fr", "kab"],
      },
      {
        type: "doctor",
        name_en: "Dr. Boualem Djeridane",
        name_ar: "د. بوعلام جريدان",
        name_fr: "Dr Boualem DJERIDANE",
        specialty: "general",
        specialty_ar: "طب عام",
        address: "Cité 1100 Logts Bouira Bt 1, Bouira 10000",
        wilaya: "Bouira",
        coordinates: { lat: 36.3790, lng: 3.9010 },
        phone: "+213 026736667",
        consultationFee: 1500,
        languages: ["ar", "fr", "kab"],
      },
      // === KHENCHELA (1) ===
      {
        type: "doctor",
        name_en: "Dr. L. Daghbouche Mohamed",
        name_ar: "د. ل. دغبوش محمد",
        name_fr: "Dr L. DAGHBOUCHE MOHAMED",
        specialty: "general",
        specialty_ar: "طب عام",
        address: "Cité Boudjalbana, Khenchela 40000",
        wilaya: "Khenchela",
        coordinates: { lat: 35.4358, lng: 7.1430 },
        phone: "+213 771438421",
        consultationFee: 1500,
        languages: ["ar", "fr"],
      },
    ];

    for (const doctor of sampleDoctors) {
      await ctx.db.insert("doctors", {
        ...doctor,
        rating: Math.round((3 + Math.random() * 2) * 10) / 10,
        reviewCount: Math.floor(Math.random() * 50),
        isVerified: true,
        isActive: true,
        createdAt: Date.now(),
        updatedAt: Date.now(),
      });
    }

    return { success: true, count: sampleDoctors.length }; // 155 entries: 102 doctors (32 original + 35 batch 2 + 35 batch 3) + 50 clinics + 3 hospitals
  },
});
