import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { motion } from 'framer-motion'
import { useLanguage } from './hooks/useLanguage'
import './App.css'

const content = {
  en: { nav:['Discover','Stay','Taste','Plan'],signIn:'Sign in',join:'Join Hasio',switch:'العربية',eyebrow:'THE OASIS, CURATED',titleA:'Al-Ahsa,',titleB:'beyond the expected.',intro:'A considered guide to the world’s largest oasis—rare stays, storied places, and local encounters selected with care.',explore:'Explore the oasis',plan:'Plan with Hasio',search:'Search places, stays, experiences…',storyKicker:'THE HASIO EDIT',storyTitle:['Travel slowly.','Remember deeply.'],storyBody:'We look beyond the obvious to bring you closer to the people, flavours and landscapes that give Al-Ahsa its soul.',why:'Why travel with us',values:[['Locally considered','Recommendations shaped by people who know the oasis by heart.'],['Quietly exceptional','Distinctive stays and experiences, chosen for character—not crowds.'],['Effortlessly yours','Save, plan and book your entire escape from one beautifully simple place.']],collectionKicker:'CURATED COLLECTIONS',collectionTitle:'Choose your way into the oasis',collections:[['Ancient & alive','Walk through living history','HERITAGE'],['Under the palms','Slow mornings, shaded paths','NATURE'],['A table of stories','Taste the region at its source','FLAVOURS']],serviceKicker:'YOUR PERSONAL CONCIERGE',serviceTitle:['One journey.','Entirely your own.'],serviceBody:'Tell Hasio what moves you. Our intelligent planner turns your pace, tastes and travel dates into a considered Al-Ahsa itinerary.',serviceCta:'Create my journey',quote:'“The beauty of Al-Ahsa is not only what you see. It is how time feels while you are here.”',finalTitle:'The oasis is waiting.',finalBody:'Begin with a place. Leave with a story.',finalCta:'Start exploring'},
  ar: { nav:['اكتشف','الإقامة','المذاق','خطط'],signIn:'تسجيل الدخول',join:'انضم إلى هاسيو',switch:'English',eyebrow:'الواحة، كما لم ترها من قبل',titleA:'الأحساء،',titleB:'أبعد من المتوقّع.',intro:'دليلك المختار بعناية إلى أكبر واحة في العالم—إقامات نادرة، أماكن تحكي التاريخ، وتجارب محلية أصيلة.',explore:'استكشف الواحة',plan:'خطط مع هاسيو',search:'ابحث عن أماكن وإقامات وتجارب…',storyKicker:'اختيارات هاسيو',storyTitle:['تمهّل في رحلتك.','واصنع ذكرى أعمق.'],storyBody:'نأخذك إلى ما وراء المألوف، لتقترب من الناس والنكهات والطبيعة التي تمنح الأحساء روحها.',why:'لماذا تسافر معنا',values:[['برؤية محلية','توصيات يصنعها من يعرف الواحة عن قرب.'],['استثنائي بهدوء','إقامات وتجارب لها طابعها الخاص، بعيداً عن الزحام.'],['رحلتك ببساطة','احفظ وخطط واحجز رحلتك كاملة من مكان واحد جميل وسهل.']],collectionKicker:'مجموعات مختارة',collectionTitle:'اختر طريقك إلى قلب الواحة',collections:[['عريق ومتجدد','سر بين صفحات التاريخ الحي','التراث'],['تحت ظلال النخيل','صباحات هادئة ودروب ظليلة','الطبيعة'],['مائدة من الحكايات','تذوق المنطقة من مصدرها','النكهات']],serviceKicker:'مرشدك الشخصي',serviceTitle:['رحلة واحدة.','مصممة لك.'],serviceBody:'أخبر هاسيو بما تحب. يحوّل مخططنا الذكي وقتك وذوقك وتواريخ سفرك إلى برنامج مدروس للأحساء.',serviceCta:'صمّم رحلتي',quote:'«جمال الأحساء ليس فقط فيما تراه، بل في إحساس الوقت وأنت هنا.»',finalTitle:'الواحة بانتظارك.',finalBody:'ابدأ بمكان، وعد بحكاية.',finalCta:'ابدأ الاستكشاف'}
}
const photos=['https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1000&q=85','https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1000&q=85','https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=85']
const reveal={initial:{opacity:0,y:28},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.2},transition:{duration:.7}}

export default function App(){
 const {lang,toggleLang,isRtl}=useLanguage(),t=content[lang],navigate=useNavigate(); const [menu,setMenu]=useState(false),[query,setQuery]=useState('')
 const search=e=>{e.preventDefault();navigate(query.trim()?`/listings?search=${encodeURIComponent(query)}`:'/listings')}
 return <main className={`home-redesign ${isRtl?'rtl':''}`} dir={isRtl?'rtl':'ltr'}>
  <header className="home-nav"><Link className="wordmark" to="/home"><span className="brand-mark">H</span><span>Hasio</span></Link><nav className={menu?'nav-menu open':'nav-menu'}><Link to="/explore">{t.nav[0]}</Link><Link to="/listings?type=hotel">{t.nav[1]}</Link><Link to="/listings?type=restaurant">{t.nav[2]}</Link><a href="#concierge">{t.nav[3]}</a></nav><div className="nav-actions"><button onClick={toggleLang}>{t.switch}</button><Link className="signin" to="/sign-in">{t.signIn}</Link><Link className="join" to="/sign-up">{t.join}<span>↗</span></Link><button className="menu-button" aria-label="Menu" onClick={()=>setMenu(!menu)}>☰</button></div></header>
  <section className="hero-wrap"><div className="hero-media"/><div className="hero-shade"/><motion.div className="hero-copy" initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.9}}><span className="eyebrow light">{t.eyebrow}</span><h1>{t.titleA}<br/><em>{t.titleB}</em></h1><p>{t.intro}</p><div className="hero-buttons"><Link to="/explore" className="button cream">{t.explore}<span>↗</span></Link><button onClick={()=>document.querySelector('#concierge')?.scrollIntoView()} className="text-button">{t.plan}<span>↓</span></button></div></motion.div><form className="hero-search" onSubmit={search}><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search}/><button aria-label="Search">→</button></form><span className="hero-index">25°23′N&nbsp;&nbsp; 49°35′E</span></section>
  <section className="story section-shell"><motion.div {...reveal} className="story-heading"><span className="eyebrow">{t.storyKicker}</span><h2>{t.storyTitle[0]}<br/><em>{t.storyTitle[1]}</em></h2></motion.div><motion.div {...reveal} className="story-copy"><p>{t.storyBody}</p><Link to="/listings">{t.explore}<span>↗</span></Link></motion.div><div className="story-image"><img src="/ChatGPT Image 19 juil. 2026, 13_15_21.png" alt="Al-Ahsa landscape"/></div><div className="values"><h3>{t.why}</h3>{t.values.map((v,i)=><motion.article {...reveal} key={v[0]}><span>0{i+1}</span><h4>{v[0]}</h4><p>{v[1]}</p></motion.article>)}</div></section>
  <section className="collections section-shell"><div className="section-title"><div><span className="eyebrow">{t.collectionKicker}</span><h2>{t.collectionTitle}</h2></div><Link to="/listings">{t.explore} ↗</Link></div><div className="card-grid">{t.collections.map((c,i)=><Link to="/listings" className="collection-card" key={c[0]}><img src={photos[i]} alt=""/><div className="card-overlay"/><span className="card-tag">{c[2]}</span><div className="card-copy"><h3>{c[0]}</h3><p>{c[1]}</p></div><b>↗</b></Link>)}</div></section>
  <section className="concierge" id="concierge"><div className="concierge-photo"/><motion.div {...reveal} className="concierge-copy"><span className="eyebrow light">{t.serviceKicker}</span><h2>{t.serviceTitle[0]}<br/>{t.serviceTitle[1]}</h2><p>{t.serviceBody}</p><Link to="/services" className="button cream">{t.serviceCta}<span>↗</span></Link></motion.div><div className="planner-card"><div className="planner-top"><span className="brand-mark">H</span><div><b>Hasio Concierge</b><small><i/> Online</small></div></div><p>“A quiet three-day escape with heritage, palms and memorable local food.”</p>{[['Old Hofuf','Souq, architecture & slow lunch'],['Oasis paths','Private palms & golden hour'],['Al Qarah','Caves & an open-air supper']].map((r,i)=><div className="planner-route" key={r[0]}><span>0{i+1}</span><div><b>{r[0]}</b><small>{r[1]}</small></div></div>)}</div></section>
  <section className="quote section-shell"><span>✦</span><blockquote>{t.quote}</blockquote><small>— HASIO FIELD NOTES, VOL. 01</small></section><section className="final-cta section-shell"><div><span className="eyebrow">YOUR STORY STARTS HERE</span><h2>{t.finalTitle}</h2><p>{t.finalBody}</p></div><Link to="/explore" className="round-link">{t.finalCta}<span>↗</span></Link></section>
  <footer className="home-footer"><Link className="wordmark" to="/home"><span className="brand-mark">H</span><span>Hasio</span></Link><p>Curating the soul of Al-Ahsa.</p><div><Link to="/listings">Explore</Link><Link to="/services">Concierge</Link><a href="/privacy-policy.html">Privacy</a></div><small>© 2026 HASIO</small></footer>
 </main>
}
